[project]
name = "worstcase"
version = "0.6.0"
description = "Worst case analysis and sensitivity studies. Extreme Value, Root-Sum-Square, Monte Carlo."
authors = [{name="Alex Osborne", email="alex@osborneee.com"}]
license = "MIT"
readme = "README.md"
repository = "https://github.com/amosborne/worstcase"
requires-python = ">=3.10"
dependencies = ["networkx (>=3.3)", "numpy (>=2.2)", "pyDOE (>=1.0)"]

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.6.0"
isort = "^8.0.0"
black = "^22"
flake8 = "^7.3.0"
flake8-pyproject = "^1.2.4"
pytest = "^9.0.3"
pytest-randomly = "^4.1.0"
pytest-cov = "^7.1.0"
Pint = "^0.24.4"
# https://github.com/connorferster/forallpeople/issues/119
forallpeople = { git = "https://github.com/eosti/forallpeople.git", branch = "equality-operator" }

[tool.poetry.group.examples]
optional = true

[tool.poetry.group.examples.dependencies]
jupyterlab = "^3.0.15"
matplotlib = "^3.4.2"
jupyterlab-code-formatter = "^1.5.3"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"
extend-exclude = "*.ipynb_checkpoints*,.venv,dist"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
